export const GET_INTERVENTIONS = 'GET_INTERVENTIONS';
export const GET_INTERVENTIONS_SUCCESS = 'GET_INTERVENTIONS_SUCCESS';
export const GET_INTERVENTIONS_ERROR = 'GET_INTERVENTIONS_ERROR';

export const CREATE_INTERVENTIONS = 'CREATE_INTERVENTIONS';

export const SORT_BY_DATE = 'SORT_BY_DATE';
