export const GET_INTERVENTIONS = 'GET_INTERVENTIONS';
export const GET_INTERVENTIONS_SUCCESS = 'GET_INTERVENTIONS_SUCCESS';
export const GET_INTERVENTIONS_ERROR = 'GET_INTERVENTIONS_ERROR';

export const CREATE_INTERVENTIONS = 'CREATE_INTERVENTIONS';

export const SORT_INTER_ASC = 'SORT_INTER_ASC';
export const SORT_INTER_DESC = 'SORT_INTER_DESC';
